# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20170221_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='correct',
            field=models.BooleanField(default=0),
        ),
    ]
